extract_drivers <- function(data){
  
  # This script converts extracted text fields into binary indicator columns for measured variables, drivers, and variables that responded to water level change. 
  
combined_vars <- data |> 
  mutate(
    #---------------- DRIVERS ----------------#
    tp_drive  = ifelse(grepl("TP", chem_drive, ignore.case = TRUE), 1, 0),
    tn_drive  = ifelse(grepl("TN", chem_drive, ignore.case = TRUE), 1, 0),
    nh4_drive = ifelse(grepl("NH4", chem_drive, ignore.case = TRUE), 1, 0),
    ph_drive  = ifelse(grepl("pH", chem_drive, ignore.case = TRUE), 1, 0),
    do_drive  = ifelse(grepl("DO", chem_drive, ignore.case = TRUE), 1, 0),
    srp_drive = ifelse(grepl("SRP", chem_drive, ignore.case = TRUE), 1, 0),
    no3_drive = ifelse(grepl("NO3", chem_drive, ignore.case = TRUE), 1, 0),
    cond_drive = ifelse(grepl("conductivity", chem_drive, ignore.case = TRUE), 1, 0),
    metals_drive = ifelse(grepl("metals", chem_drive, ignore.case = TRUE), 1, 0),
    orp_drive = ifelse(grepl("ORP", chem_drive, ignore.case = TRUE), 1, 0),
    no2_drive = ifelse(grepl("NO2", chem_drive, ignore.case = TRUE), 1, 0),
    dic_drive = ifelse(grepl("DIC", chem_drive, ignore.case = TRUE), 1, 0),
    dom_drive = ifelse(grepl("DOM", chem_drive, ignore.case = TRUE), 1, 0),
    pom_drive = ifelse(grepl("POM", chem_drive, ignore.case = TRUE), 1, 0),
    tkn_drive = ifelse(grepl("TKN", chem_drive, ignore.case = TRUE), 1, 0),
    doc_drive = ifelse(grepl("DOC", chem_drive, ignore.case = TRUE), 1, 0),
    din_drive = ifelse(grepl("DIN", chem_drive, ignore.case = TRUE), 1, 0),
    salinity_drive = ifelse(grepl("salinity", chem_drive, ignore.case = TRUE), 1, 0),
    other_chem_drive = ifelse(grepl("Other", chem_drive, ignore.case = TRUE), 1, 0),
    
    water_level_drive = ifelse(grepl("water level", phys_drive, ignore.case = TRUE), 1, 0),
    water_temp_drive  = ifelse(grepl("water temperature", phys_drive, ignore.case = TRUE), 1, 0),
    transparency_drive = ifelse(grepl("transparency", phys_drive, ignore.case = TRUE), 1, 0),
    turb_drive = ifelse(grepl("turbidity", phys_drive, ignore.case = TRUE), 1, 0),
    light_drive = ifelse(grepl("PAR", phys_drive, ignore.case = TRUE), 1, 0),
    tss_tds_drive = ifelse(grepl("total suspended solids|tss|tds|total dissolved solid", phys_drive, ignore.case = TRUE), 1, 0),
    strat_drive = ifelse(grepl("mix|stab|strat", phys_drive, ignore.case = TRUE), 1, 0),
    restime_drive = ifelse(grepl("residence", phys_drive, ignore.case = TRUE), 1, 0),
    flush_discharge_drive = ifelse(grepl("flush|discharge", phys_drive, ignore.case = TRUE), 1, 0),
    inflow_drive = ifelse(grepl("inflow", phys_drive, ignore.case = TRUE), 1, 0),
    precip_drive = ifelse(grepl("precip|rain", phys_drive, ignore.case = TRUE), 1, 0),
    air_temp_drive = ifelse(grepl("air", phys_drive, ignore.case = TRUE), 1, 0),
    other_phys_drive = ifelse(grepl("Other", phys_drive, ignore.case = TRUE), 1, 0),
    
    #---------------- RESPONSES ----------------#
    not_assessed_response = ifelse(grepl("not assessed", phys_response, ignore.case = TRUE), 1, 0),
    water_temp_response = ifelse(grepl("water temperature", phys_response, ignore.case = TRUE), 1, 0),
    transparency_response = ifelse(grepl("transparency", phys_response, ignore.case = TRUE), 1, 0),
    turb_response = ifelse(grepl("turbidity", phys_response, ignore.case = TRUE), 1, 0),
    light_response = ifelse(grepl("PAR", phys_response, ignore.case = TRUE), 1, 0),
    tss_tds_response = ifelse(grepl("total suspended solids|tss|tds|total dissolved solid|sediment resuspension", phys_response, ignore.case = TRUE), 1, 0),
    other_phys_response = ifelse(grepl("Other", phys_response, ignore.case = TRUE), 1, 0),
    watercolor_response = ifelse(grepl("water color", phys_response, ignore.case = TRUE), 1, 0),
    
    tp_response  = ifelse(grepl("TP", chem_response, ignore.case = TRUE), 1, 0),
    tn_response  = ifelse(grepl("TN", chem_response, ignore.case = TRUE), 1, 0),
    nh4_response = ifelse(grepl("NH4", chem_response, ignore.case = TRUE), 1, 0),
    ph_response  = ifelse(grepl("pH", chem_response, ignore.case = TRUE), 1, 0),
    do_response  = ifelse(grepl("DO", chem_response, ignore.case = TRUE), 1, 0),
    srp_response = ifelse(grepl("SRP", chem_response, ignore.case = TRUE), 1, 0),
    no3_response = ifelse(grepl("NO3", chem_response, ignore.case = TRUE), 1, 0),
    cond_response = ifelse(grepl("conductivity", chem_response, ignore.case = TRUE), 1, 0),
    metals_response = ifelse(grepl("metals", chem_response, ignore.case = TRUE), 1, 0),
    orp_response = ifelse(grepl("ORP", chem_response, ignore.case = TRUE), 1, 0),
    no2_response = ifelse(grepl("NO2", chem_response, ignore.case = TRUE), 1, 0),
    doc_response = ifelse(grepl("DOC", chem_response, ignore.case = TRUE), 1, 0),
    dic_response = ifelse(grepl("DIC", chem_response, ignore.case = TRUE), 1, 0),
    dom_response = ifelse(grepl("DOM", chem_response, ignore.case = TRUE), 1, 0),
    pom_response = ifelse(grepl("POM", chem_response, ignore.case = TRUE), 1, 0),
    tkn_response = ifelse(grepl("TKN", chem_response, ignore.case = TRUE), 1, 0),
    din_response = ifelse(grepl("DIN", chem_response, ignore.case = TRUE), 1, 0),
    salinity_response = ifelse(grepl("salinity", chem_response, ignore.case = TRUE), 1, 0),
    other_chem_response = ifelse(grepl("Other", chem_response, ignore.case = TRUE), 1, 0),
    
    #---------------- VARIABLES MEASURED ----------------#
    filt_chla_vars = ifelse(grepl("filtered chlorophyll", bio_vars, ignore.case = TRUE), 1, 0),
    phyto_micros_vars = ifelse(grepl("phytoplankton microscopy", bio_vars, ignore.case = TRUE), 1, 0),
    single_cyano_taxon_vars = ifelse(grepl("single cyanobacterial taxon", bio_vars, ignore.case = TRUE), 1, 0),
    sensor_chla_vars = ifelse(grepl("sensor", bio_vars, ignore.case = TRUE), 1, 0),
    other_bio_vars = ifelse(grepl("Other", bio_vars, ignore.case = TRUE), 1, 0),
    
    tp_vars  = ifelse(grepl("TP", chem_vars, ignore.case = TRUE), 1, 0),
    tn_vars  = ifelse(grepl("TN", chem_vars, ignore.case = TRUE), 1, 0),
    nh4_vars = ifelse(grepl("NH4", chem_vars, ignore.case = TRUE), 1, 0),
    ph_vars  = ifelse(grepl("pH", chem_vars, ignore.case = TRUE), 1, 0),
    do_vars  = ifelse(grepl("DO", chem_vars, ignore.case = TRUE), 1, 0),
    srp_vars = ifelse(grepl("SRP", chem_vars, ignore.case = TRUE), 1, 0),
    no3_vars = ifelse(grepl("NO3", chem_vars, ignore.case = TRUE), 1, 0),
    cond_vars = ifelse(grepl("conductivity", chem_vars, ignore.case = TRUE), 1, 0),
    metals_vars = ifelse(grepl("metals", chem_vars, ignore.case = TRUE), 1, 0),
    orp_vars = ifelse(grepl("ORP", chem_vars, ignore.case = TRUE), 1, 0),
    no2_vars = ifelse(grepl("NO2", chem_vars, ignore.case = TRUE), 1, 0),
    doc_vars = ifelse(grepl("DOC", chem_vars, ignore.case = TRUE), 1, 0),
    dic_vars = ifelse(grepl("DIC", chem_vars, ignore.case = TRUE), 1, 0),
    dom_vars = ifelse(grepl("DOM", chem_vars, ignore.case = TRUE), 1, 0),
    pom_vars = ifelse(grepl("POM", chem_vars, ignore.case = TRUE), 1, 0),
    tkn_vars = ifelse(grepl("TKN", chem_vars, ignore.case = TRUE), 1, 0),
    din_vars = ifelse(grepl("DIN", chem_vars, ignore.case = TRUE), 1, 0),
    salinity_vars = ifelse(grepl("salinity", chem_vars, ignore.case = TRUE), 1, 0),
    other_chem_vars = ifelse(grepl("Other", chem_vars, ignore.case = TRUE), 1, 0),
    
    water_level_vars = ifelse(grepl("water level", phys_vars, ignore.case = TRUE), 1, 0),
    water_temp_vars  = ifelse(grepl("water temperature", phys_vars, ignore.case = TRUE), 1, 0),
    transparency_vars = ifelse(grepl("transparency", phys_vars, ignore.case = TRUE), 1, 0),
    turb_vars = ifelse(grepl("turbidity", phys_vars, ignore.case = TRUE), 1, 0),
    light_vars = ifelse(grepl("PAR", phys_vars, ignore.case = TRUE), 1, 0),
    tss_tds_vars = ifelse(grepl("total suspended solids|tss|tds|total dissolved solid|sediment resuspension", phys_vars, ignore.case = TRUE), 1, 0),
    other_phys_vars = ifelse(grepl("Other", phys_vars, ignore.case = TRUE), 1, 0))

}
